spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

# отключаем Config Server и Eureka
  cloud:
    discovery:
      enabled: false
  eureka:
    client:
      enabled: false
